# Use the official Node.js 18 image as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /backend

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY backend/ ./

# Expose the port the app runs on
EXPOSE 3000

# Run Prisma migrations
RUN npx prisma generate

# Start the application
CMD ["node", "src/server.js"]